so2zy/so2zy_FE

src/mocks/handlers.js
src/pages/placeDetail/components/PlaceDetail.page.tsx

📌 **작업 내용**
- api명세서대로 데이터 구조 변경
📌 **확인 사항**

Feat: 데이터 구조 변경

---

src/mocks/handlers.js
src/pages/placeDetail/components/PlaceDetail.page.tsx

📌 **작업 내용**
데이터 구조 수정
📌 **확인 사항**
회의 후에 수정부분 반영

MINI-21--feat/placeDetail/data

---

src/components/common/Item/Item.tsx

Design: gray색 변경

---

.eslintrc
.vscode/settings.json
src/App.tsx
src/components/common/Card/Card.tsx
src/components/common/Header/Header.tsx
src/components/common/Item/Item.tsx
src/mocks/handlers.js
src/pages/cart/Cart.page.tsx
src/pages/confirm/Confirm.page.tsx
src/pages/main/components/getPlaces.ts
src/pages/main/components/mainAllListItem.tsx
src/pages/main/components/mainListItem.tsx
src/pages/placeDetail/PlaceDetail.page.tsx
src/pages/placeDetail/components/MapModal.tsx
src/pages/placeDetail/index.ts
src/pages/reservation/Reservation.page.tsx
src/pages/reservation/components/ReservationAgree.tsx
src/pages/reservation/components/ReservationBtn.tsx
src/pages/reservation/components/ReservationDesc.tsx
src/styles/theme.ts

📌 **작업 내용**
📌 **확인 사항**
종수님이랑 제가 일단 급해서 올리는거라 예약, 예약확인, 장바구니는 기능 맡으신 분들이 추가로 디자인 손보시면 될거 같습니다.

Mini 35  feat/confirm

---

src/pages/signIn/components/SignIn.tsx

📌 **작업 내용**
이메일 ,비밀번호 state관리
📌 **확인 사항**
이메일 비밀번호 state가 누락되있어서 수정

MINI-41--feat/token/manageEmail

---

src/pages/main/components/mainAllListItem.tsx
src/pages/main/components/mainListContainer.tsx
src/pages/main/components/mainListItem.tsx
src/pages/main/components/regionModal.tsx

📌 **작업 내용**
불필요한 주석 제거 
📌 **확인 사항**

Feat: 불필요한 주석 제거

---

package-lock.json
package.json
src/components/common/Loading/Loading.tsx
src/components/common/Loading/index.ts
src/pages/placeDetail/PlaceDetail.page.tsx

📌 **작업 내용**
로딩 컴포넌트 추가
📌 **확인 사항**

MINI-4--feat/placeDetail

---

src/components/common/Loading/Loading.tsx
src/components/common/NotFound/NotFound.tsx

📌 **작업 내용**
공통 컴포넌트 수정
📌 **확인 사항**

Mini 47  feat/place detail/common component

---

src/components/common/Header/Header.tsx
src/pages/main/components/getPlaces.ts
src/pages/main/components/mainAllListItem.tsx
src/pages/main/components/mainListItem.tsx
src/utils/useFormatDate.ts

📌 **작업 내용**
1. 상세페이지에 startDate, endDate, personnel 데이터 넘겨주기
2. Header에서 검색어 입력하면 관련 쿼리로 이동하는 것 에러 해결 
-> 엔터 쳐야 이동하는 것으로 수정
📌 **확인 사항**

Feat: 상세페이지 props 연결 및 검색 결과 에러 해결

---

src/pages/main/components/regionModal.tsx

📌 **작업 내용**
cursor 포인터 추가
📌 **확인 사항**

Feat: cursor 포인터 추가

---

src/pages/main/components/mainListItem.tsx
src/pages/main/components/regionModal.tsx
src/pages/main/components/regionSelectBtn.tsx

📌 **작업 내용**
1. 메인페이지 지역 선택 버튼 줄 간격 수정
2. 메인페이지 box-shadow 수정
📌 **확인 사항**

Style: 메인페이지 및 모달창 css 수정

---

package-lock.json
src/components/common/Footer/Footer.tsx
src/components/common/Header/Header.tsx
src/pages/signIn/components/SignIn.tsx
src/pages/signUp/components/SignUp.tsx

📌 **작업 내용**
회원가입 , 로그인, 푸터 style수정
📌 **확인 사항**

Mini 61  fix/style/one

---

package-lock.json
src/components/common/Footer/Footer.tsx
src/components/common/Header/Header.tsx
src/pages/signIn/components/SignIn.tsx
src/pages/signUp/components/SignUp.tsx

📌 **작업 내용**
회원가입 , 로그인, 푸터 style수정
📌 **확인 사항**

Mini 60  fix/style

---

src/pages/cart/Cart.page.tsx

Design: 디자인 수정

---

src/components/common/Header/Header.tsx
src/pages/signIn/components/SignIn.tsx

📌 **작업 내용**
로그인 로그아웃시 alert추가
📌 **확인 사항**
로그인 로그아웃시 alert추가

hotfix:로그인 로그아웃 alert추가

---

src/components/common/ScrollToTop/ScrollToTop.tsx
src/pages/cart/Cart.page.tsx
src/pages/main/components/mainAllListItem.tsx
src/pages/main/components/mainListItem.tsx

📌 **작업 내용**
피드백
1. 0원 받을 때 품절 처리 -> isAvaliable O
2. 체크박스 같은 호텔에서 두개 입력했을 때 같이 선택되는 것 O
3. 장바구니 이미지 깨짐 O 
4. 스크롤 최상단 버튼 위치 수정 O
5. 전체 선택 하나로 합치기 O 
📌 **확인 사항**

Mini 65  hotfix/main cart

---

src/components/common/Footer/Footer.tsx
src/components/common/Header/Header.tsx

style: 푸터 수정

---

src/components/common/Header/Header.tsx

Design: Header 수정

---

src/pages/placeDetail/PlaceDetail.page.tsx

Feat: 2조 최종 제출

---

src/pages/placeDetail/PlaceDetail.page.tsx
src/pages/placeDetail/components/CalendarModal.tsx

Feat: 상세 페이지 필터링 post 수정

---

src/pages/cartReservation/CartReservation.page.tsx
src/pages/cartReservation/components/postCartReservation.ts
src/pages/confirm/Confirm.page.tsx
src/pages/main/components/getPlaces.ts
src/pages/main/components/mainAllListItem.tsx
src/pages/main/components/mainListItem.tsx

📌 **작업 내용**
1. 장바구니 -> 예약 post 를 useMutation으로 코드 분리 
2. 품절 시 빨간 글자 처리
📌 **확인 사항**

Mini 71  refactor/main

---

src/pages/placeDetail/PlaceDetail.page.tsx

Refactor: useCallback 사용으로 리렌더링 최소화

---

src/pages/placeDetail/PlaceDetail.page.tsx

Refactor: 모달 중복 코드 수정

---

src/components/FilterButtons/FilterButtons.tsx
src/components/FilterButtons/index.ts
src/components/SortButtons/SortButtons.tsx
src/components/SortButtons/index.ts
src/index.tsx
src/pages/regionList/RegionList.page.tsx
src/pages/searchList/SearchList.page.tsx
src/utils/formatDateRange.ts
src/utils/shortenPrice.ts

📌 **작업 내용**
- 무한스크롤 첫 렌더링 시, 2개 페이지 가져오는 이슈 해결 (1페이지만)
- 함수 모듈화
- 컴포넌트화
- 불필요한 코드 삭제
📌 **확인 사항**
- 동민님이 말씀 없으셔서 일단 FE 단에서 개선해야할 작업은 다 끝낸 듯 합니다

Mini 73  refactor/region search

---

src/components/common/Header/Header.tsx
src/pages/signIn/components/SignIn.tsx

📌 **작업 내용**
accesstoken재발급 부분 , 비동기 처리 수정 
📌 **확인 사항**

fix:accesstoken 재발급 수정

---

src/pages/signIn/components/SignIn.tsx
src/pages/signUp/components/SignUp.tsx

📌 **작업 내용**
회원가입 ,로그인 페이지 스타일 수정
📌 **확인 사항**

Mini 78  refactor/sign up sign in/style

---

src/components/common/Header/Header.tsx
src/pages/signIn/components/SignIn.tsx
src/pages/signUp/components/SignUp.tsx

📌 **작업 내용**
accessToken 재발급 수정
로그인 회원가입 페이지 스타일 수정
📌 **확인 사항**

Mini 76  refactor/singn up sign in

---

package-lock.json
package.json
src/pages/cart/Cart.page.tsx
tsconfig.json

Test: jest 세팅 및 테스트
